#1. [package]是一个片段（section）标题，表明下面的语句用来配置一个包。
[package]
name = "hello-cargo-02"  #项目的名称
version = "0.1.0"        #项目的版本
edition = "2021"         #使用的Rust版本



#2. [dependencies]是罗列项目依赖的片段的开始。在 Rust 中，代码包被称为 crates。
[dependencies]
